# Generated by Django 3.0.6 on 2020-05-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user1',
        ),
    ]
