# Generated by Django 3.0.6 on 2020-05-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200527_2357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user1',
        ),
    ]
