# Generated by Django 3.0.6 on 2020-06-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_delete_user1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=70)),
                ('Email', models.EmailField(default='', max_length=70)),
                ('MobileNumber', models.IntegerField(default=0)),
                ('WhatsappNumber', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=700)),
            ],
        ),
    ]
