# Generated by Django 3.0.6 on 2020-06-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200616_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='timestamp',
        ),
    ]
