# Generated by Django 3.0.6 on 2020-06-16 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_orderupdate_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='update_desc',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='update_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
