# Generated by Django 3.0.6 on 2020-06-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200616_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='update_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
