# Generated by Django 3.0.6 on 2020-06-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20200616_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='value',
        ),
    ]
