# Generated by Django 3.0.6 on 2020-06-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
