# Generated by Django 3.0.6 on 2020-06-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_order_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
    ]
