# Generated by Django 3.0.6 on 2020-06-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
