# Generated by Django 3.0.6 on 2020-06-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
